/** C program that calculates the lift generated by an airfoil based on the
 * Bernoulli equation, taking into account the air density, air velocity, and
 * angle of attack of the airfoil
 */

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#define PI 3.14159265358979323846

double rand_range(double min, double max) {
  double range = max - min;
  double random_num = ((double)rand()) / RAND_MAX;
  return (random_num * range) + min;
}

int main() {
  srand(time(NULL));

  // Input parameters with measurement uncertainties
  double rho = rand_range(
      1.22, 1.28); // air density in kg/m^3 (measured with +/- 2% accuracy)
  double v = rand_range(
      8.0, 12.0); // air velocity in m/s (measured with +/- 5% accuracy)
  double alpha = rand_range(
      -5.0,
      5.0); // angle of attack in degrees (measured with +/- 1 degree accuracy)

  // Constants with known values
  double c = 1.0;           // chord length of the airfoil in meters
  double cl_alpha = 2 * PI; // lift curve slope in radians
  double cl_0 = 0.1;        // zero-lift coefficient
  double cd_0 = 0.01;       // zero-lift drag coefficient
  double area = c * 1.0;    // planform area of the airfoil in m^2

  // Calculations
  double alpha_rad = alpha * PI / 180.0;   // convert angle of attack to radians
  double cl = cl_0 + cl_alpha * alpha_rad; // lift coefficient
  double cd = cd_0 + cl * cl / (PI * 1.0 * 0.8); // drag coefficient
  double lift = 0.5 * rho * v * v * cl * area;   // lift in Newtons
  double drag = 0.5 * rho * v * v * cd * area;   // drag in Newtons

  // Print results
  printf("Air density: %.3f kg/m^3\n", rho);
  printf("Air velocity: %.3f m/s\n", v);
  printf("Angle of attack: %.3f degrees\n", alpha);
  printf("Lift generated by the airfoil: %.3f N\n", lift);
  printf("Drag generated by the airfoil: %.3f N\n", drag);

  return 0;
}

/**
 * @brief In this program, I have introduced measurement uncertainties for the
    air density, air velocity, and angle of attack of the airfoil. I assume that
    the air density is measured with an accuracy of +/- 2%, the air velocity is
    measured with an accuracy of +/- 5%, and the angle of attack is measured
    with an accuracy of +/- 1 degree. I use a random number generator to
    generate values for these input parameters within the specified ranges.

    I also introduced several constants with known values, such as the chord
    length of the airfoil, the lift curve slope, the zero-lift coefficient, the
    zero-lift drag coefficient, and the planform area of the airfoil.

    Based on these input parameters and constants, I calculate the lift and drag
    generated by the airfoil using the Bernoulli equation and the lift and drag
    coefficients, which are calculated based on the angle of attack using a
    linear approximation.

    For the measurement uncertainties, I assume uniform distributions with the
    specified ranges.
 *
 */
